version: '3.9'
services:
  product:
    image: postgres:latest
    container_name: product
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

volumes:
  product_data:
